name: Build and copy production assets to a build branch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 16.18.x
          cache: npm
          check-latest: true
      - name: Install NPM dependencies and Compile assets for Production
        run: |
          npm install
          npm run build
      - name: List Output Files
        run: ls
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: $
          MESSAGE: "Build: {{sha}} {msg}"